# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC04Prueba():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC04Prueba(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(968, 695)
    self.driver.find_element(By.ID, "searchBox").click()
    self.driver.find_element(By.ID, "searchBox").send_keys("dress")
    self.driver.find_element(By.ID, "searchButton").click()
    self.driver.find_element(By.CSS_SELECTOR, "table:nth-child(2) td:nth-child(3) #itemImage").click()
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    self.driver.find_element(By.CSS_SELECTOR, "table:nth-child(3) td:nth-child(4) #itemImage").click()
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    self.driver.find_element(By.LINK_TEXT, "CART 2").click()
    self.driver.find_element(By.LINK_TEXT, "Proceed to checkout").click()
  
